### ISSUE TITLE
Jicofo and Prosody containers keep restarting with fatal error "Jicofo component secret and auth password must be set"

### ISSUE THREAD

**Issue by dvmc** [jitsi/docker-jitsi-meet#1004]
After running docker-compose, the Jicofo and Prosody containers keep restarting every few seconds. The logs provide a fatal error. Below they are in full. The log pattern repeats identically after every restart and from what I can see they are identical for both containers (jicofo and prosody).

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
FATAL ERROR: Jicofo component secret and auth password must be set
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

I have tried it with the currently most recent branch (`1fa5048`). What I don't understand is why the error message appears in the logs, although it is only echoed in `prosody/rootfs/etc/cont-init.d/10-config` of the last stable branch (`tags/stable-5390-3`).

If I add a `JICOFO_COMPONENT_SECRET` to `.env`, the containers don't keep restarting. However, the Websocket connection of the web interface returns 403, but that might be for another issue.

**Comment by FlambierterHamburger** [comment]
Hi, I had the same problem yesterday after reinstalling because of changed domains. It seems, that a recent commit broke the JiFoCo setup script. I pulled `git checkout cb4d9413b7481b9767ff5d2ec09e22bdc76e74e3`, deleted all config folders and made a new setup and it was working again.
Hope this helps.

**Comment by saghul** [comment]
Do not use master unless you build the unstable images yourself. Use a release.

**Comment by dvmc** [comment]
Well, apparently I was too quick on reading the guide. Thanks for the heads up!

However, I still think this is easy to overlook. I'll open a pull request on the docs for a suggestion.

**Comment by saghul** [comment]
> I'll open a pull request on the docs for a suggestion.

Thank you!

**Comment by J4gQBqqR** [comment]
> Do not use master unless you build the unstable images yourself. Use a release.

I had the same issue when trying to upgrade to the stable release "stable-5390-3".
Is this expected? Could you help me understand if this means that every time when we upgrade in the future, we have to purge the config directory and start all over again?

Could anyone help to point us to the exact place that jicofo config file is changed that caused this incompatibility issue? I would appreciate if there is a way to fix it instead of doing it from scratch.

**Comment by saghul** [comment]
Config files are now regenerated on every boot so all you need to do it download the new release, place the .env file and then stop and start. When you start make sure you pass "--force-recreate" to make sure the containers are recreated.

**Comment by dogukancagatay** [comment]
You don't have to checkout an older version.

I think *.env* and *docker-compose.yml* files are missing an environment variable.

- Add `JICOFO_COMPONENT_SECRET` environment variable to your *.env* file with a value.
- Add the variable name (`JICOFO_COMPONENT_SECRET`) to the environment variables list of *jicofo* container.

**Comment by prayagsingh** [comment]
@dogukancagatay no, master branch isn't missing any env variable. You need to build the images by yourself to use master branch else checkout the last stable version.

**Comment by dogukancagatay** [comment]
@prayagsingh I did try that but this time *jicofo* was giving a similar secret error.

```
Jicofo 2021-04-10 20:29:00.688 SEVERE: [1] org.jitsi.jicofo.Main.log() An uncaught exception occurred in thread=Thread[main,5,main]
jicofo_1   | org.jitsi.cmd.ParseException: Some of required arguments were not specified: [secret]
jicofo_1   |    at org.jitsi.cmd.CmdLine.parse(CmdLine.java:130)
jicofo_1   |    at org.jitsi.jicofo.Main.setSystemProperties(Main.java:182)
jicofo_1   |    at org.jitsi.jicofo.Main.main(Main.java:56)
```

I was able to pass that secret error, when I added `JICOFO_SECRET` to *.env* and *docker-compose.yml* files.

However, prosody connection errors occurred. (caused by prosody is not listening on port `5347`, I did not go into the detail).

So, even if there is no environment variable missing, I wasn't able to run, when I built the docker images.

**Comment by prayagsingh** [comment]
@dogukancagatay are you sure that you tried this command `FORCE_REBUILD=1 JITSI_RELEASE=unstable make`?

**Comment by dogukancagatay** [comment]
@prayagsingh  I didn't use that command, in my previous trials.

When I used that command to build, I still needed to add `JICOFO_COMPONENT_SECRET` to the *.env* file otherwise prosody (and jicofo) won't come up.

The unstable version backends are ok after that, no other errors occurred, but frontend started giving errors, so again no luck, I was able to test it.

**Comment by iankaufmann** [comment]
> @prayagsingh I didn't use that command, in my previous trials.
> 
> When I used that command to build, I still needed to add `JICOFO_COMPONENT_SECRET` to the _.env_ file otherwise prosody (and jicofo) won't come up.
> 
> The unstable version backends are ok after that, no other errors occurred, but frontend started giving errors, so again no luck, I was able to test it.

I can attest to the same thing happening to me.  I ran a git pull on this repo today after not using it for a couple months.  I was getting "Jicofo component secret and auth password must be set" in the logs for jicofo until I added this to the docker-compose.yml file in the environment cars for jicofo:
- JICOFO_COMPONENT_SECRET

After stopping, removing containers, then running docker-compose up -d, everything works again.

**Comment by prayagsingh** [comment]
@dogukancagatay Can you please try the below steps?
1. Remove all the Jitsi images from your machine. Use command `docker rmi -f $(docker images -a | grep jitsi)`
2.  Clone `docker-jitsi-meet`.
3. Go to `docker-jitsi-meet` directory.
4. Run the command `FORCE_REBUILD=1 JITSI_RELEASE=unstable JITSI_REPO=jitsi make`.
5. Now replace `jitsi/web:tag` with `jitsi/web:latest` image in `docker-compose.yml` file. Please do this for all the services. 
6. You can control which image to build in `STEP 4` from [here](https://github.com/jitsi/docker-jitsi-meet/blob/a6853ef5f73407aa7c07b2ffb5badcc8dd9dec88/Makefile#L5). `base` and `base-java` are mandatory hence don't remove them.

**Comment by lpyparmentier** [comment]
> Do not use master unless you build the unstable images yourself. Use a release.

FYI: it was not clear to go this way by reading the official documentation (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker). I guess that other people will do the same mistake (i.e., open a similar issue).

**Comment by saghul** [comment]
Care to make a PR clarifying the docs?

**Comment by dogukancagatay** [comment]
@prayagsingh I did as your instructions, and it worked. I didn't need to add any environment variables or change any git-tracked files.

For reference, the commit I worked on was `ce25bf67d2cf0f0235d2e25c7de65eabfca58d5f`

Thank you,

**Comment by saghul** [comment]
A new stable release is out, this is taken into account there.

**Comment by abumostafa** [comment]
Had the same problem. this worked well for me `chmod +x gen-passwords.sh && ./gen-passwords.sh`

**Comment by BlueOwlet** [comment]
Still having same problem.

When doing podman-compose up I get:

[prosody] | FATAL ERROR: Jicofo auth password must be set
[jvb]     | FATAL ERROR: JVB auth password must be set

I still get this error after doing a fresh server install and then running ./gen_passwords.sh

I can see my .env file has the passwords saved... This is really confounding to me.

**Comment by saghul** [comment]
We don't really support podman.

It's not 100% compatible with compose despite their claims.

It may work one day but we don't test it there.

**Comment by BlueOwlet** [comment]
Thank you for your reply @saghul . It is correct that podman-compse is not compatible 100% with docker. I'm very new to containers so this comes as a relief kind of surprise since I've been using podman all along and have found myself to go into rabit holes of configuration to make it work.

Using docker-compose works flawlessly.

Thank you for your guidance
