### ISSUE TITLE
Are these images to be used together on single instance?

### ISSUE THREAD

**Issue by lakshaytalkstocomputer** [jitsi/docker-jitsi-meet#1027]
What if I want to use different instance for creating multiple jibri containers. How would i connect them to meet.jitsi user defined network. Also same goes for scaling jvb.

**Comment by prayagsingh** [comment]
I would recommend using an overlay network if you are deploying jibri on a different instance. Docker-swarm is a good option here. `jitsi/jibri:latest` won't work with docker-swarm because of hardware accessibility issues but you can use `docker-compose -f jibri.yml up -d` command to make it work. Make sure to change the network to `external` in `jibri.yml` file.

**Comment by loelkes** [comment]
Scaling the videobriges is in the manual: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-scalable
