### ISSUE TITLE
confused about config directory

### ISSUE THREAD

**Issue by ralfi** [jitsi/docker-jitsi-meet#1058]
Hi all,

using latest stable 5870 it seems to meet the config var and directories are not useful to modify config anymore? How do i modyfy settings for example to set up my external turn server?

Thanks a lot.

**Comment by MrGeneration** [comment]
Because I had the same issue but didn't want to rollback I've been digging deeper in the compose stuff. 
The issue we're both experiencing is hidden here:

https://github.com/jitsi/docker-jitsi-meet/blob/d6fac8e0c38294463a535442bba3dd27327b966c/web/rootfs/etc/cont-init.d/10-config#L78-L89

Basically: To overrule the `config.js` create a copy in the same directory called `custom-config.js`. You can do the same to the `interface_config.js`. 

I don't know where the documentation is being hosted for jitsi, but I think we really should have that in the documentation. This will probably confuse a lot of users.

**Comment by ralfi** [comment]
Cooool, will try it. Thanks a lot.

**Comment by ralfi** [comment]
yeah, works ...

**Comment by MrGeneration** [comment]
@saghul so we're not planning to put remarks on above into the documentation?

**Comment by saghul** [comment]
Sure, a PR to the handbook would be most welcome.
