### ISSUE TITLE
ARM64 Support for docker images

### ISSUE THREAD

**Issue by Felixkruemel** [jitsi/docker-jitsi-meet#1069]
There are already many Jitsi related packages available for all arches, including arm64: https://download.jitsi.org/stable/

The whole docker stuff however still is only available for amd64, although there are already pretty powerful (and mostly cheaper) ARM64 Servers available on some cloud providers. Not to mention it would then also work on Raspberries (however don't know if they would be fast enough).

Can we somehow make the whole docker stuff also run on ARM64? There already was working version available on this fork, but since maintaining it alone without the community it's lacking behind a lot in terms of updates: https://github.com/amaumene/docker-jitsi-meet/

**Comment by saghul** [comment]
Sure thing, PRs are welcome. I tried this a couple of moths ago and started making some changes to make it easier, but ran into Prosody not being packaged for arm64 on their repos, which we use.

We probably want to just compile it from source.

I have looked at those forks over time and making it work just for arm is not that hard. The hard part is making a multi platform Dockerfile really, without hard coding architectures.

**Comment by Felixkruemel** [comment]
@saghul Is there an easy way to see which parts fail?
Normally `docker-compose up` should print all logs with errors, but in that case it doesn't.

![image](https://user-images.githubusercontent.com/12109804/120696378-c8f74780-c4ac-11eb-97fa-c017d37abaed.png)

**Comment by jbg** [comment]
The `exec format error` errors are because you're trying to use amd64 container images on arm64 or vice-versa.

FWIW, we're running Jicofo & Prosody container images on arm64 (both with custom Dockerfiles that build from source) and they work fine. We are still using amd64 for Jigasi (due to some issues with native libs) and Jibri (due to some issues with chromium on arm64). We haven't tried arm64 for JVB because we don't have access to big enough arm64 servers yet.

Since the Dockerfiles in this repo are mostly just installing packages from apt, and the base is `debian:buster-slim` which is already multi-architecture, the main thing would presumably be to provide an apt repository for the `arm64` arch for the Jitsi components. Once that's available I think the existing Dockerfiles should mostly work without modification.

Prosody's APT repository [already contains](https://prosody.im/download/package_repository#debianubuntu) packages for ARM64.

**Comment by jbg** [comment]
I was able to get Jigasi and Jibri both working on ARM64. Jibri (built from source) works without changes, and latest chromium, chromiumdriver, etc work fine on Debian ARM64.

Jigasi doesn't work out of the box because libjitsi bundles native libs for Opus etc and doesn't bundle any ARM64 ones. However after [patching](https://github.com/jitsi/libjitsi/pull/549) libjitsi I was able to build a `libjnopus.so` for ARM64 and drop that into the Jigasi's libs dir along with an ARM64 `libopus.so.0` and it works.

**Comment by SebastianGode** [comment]
@jbg @saghul 
I've seen that libjitsi now has ARM64 support. Is it possible to now to make the docker builds arm64 ready?
https://github.com/jitsi/libjitsi/pull/552

**Comment by SebastianGode** [comment]
Hey @saghul 
Are there any news?

**Comment by saghul** [comment]
I haven't gotten back to this yet.

**Comment by saghul** [comment]
Please follow: https://github.com/jitsi/docker-jitsi-meet/issues/1214
