### ISSUE TITLE
Prosody Config override: Use different authentication

### ISSUE THREAD

**Issue by mm28ajos** [jitsi/docker-jitsi-meet#1083]
I am trying to integrate jitsi in the matrix element app by using a [prosody plugin for authentication in this context](https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification). However, I can not change the authentication in the virtual host setting in prosody as it is overridden on docker restart. This issue may have already been addressed by [#877] but I am not sure whether I miss a point or whether restarting prosody inside the container is the only solution as of today to allow for manual prosody config changes (outside the env realm)?

Thanks in advance.

**Comment by saghul** [comment]
We don’t currently support that use case. New env vars would be needed. That would be a welcome addition.

**Comment by mm28ajos** [comment]
Created a pull request #1084

**Comment by mm28ajos** [comment]
@saghul Donyou have an indication for wether this PR might me checked?

**Comment by saghul** [comment]
I haven't gotten to it yet, sorry.

**Comment by RhysRdm** [comment]
I am looking at using this service as well. For now Ill build the docker image myself with @mm28ajos changes

**Comment by RhysRdm** [comment]
Hi @mm28ajos I have made your changes above and built the prosody docker image and I have prosody making call out and authenticating with the user service.

The problem comes after authentication the web socket gets dropped and reconnected with jitsi prosody with jitsi stating 

Sep 16 14:21:28 xxx matrix-jitsi-prosody[18318]: stanzarouter                                                 debug        Unhandled c2s stanza: iq; xmlns=urn:xmpp:extdisco:1
Sep 16 14:21:28 xxx: c2s556d0734f9b0                                              debug        Sending[c2s]: <iq to='xxx@meet.jitsi/P4Tele4v' id='xxx:sendIQ' type='error' from='meet.jitsi'>
Sep 16 14:21:29 xxx: mod_websocket

Have you seen this at all - i feel im missing something here with my config but do not know what

**Comment by mm28ajos** [comment]
I guess you should raise this question [here](https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification) as the PR only integrates the prosody module for the matrix authentication. I have, so far, not encountered this issue.
