### ISSUE TITLE
WebSocket connection to  xmpp-websocket failed

### ISSUE THREAD

**Issue by matodrobec** [jitsi/docker-jitsi-meet#1154]
I have a standard Jitsi Meet Docker stable-6433 setup. I have problem with WebSocket connection. I do not have error in Jist web container.

I'd greatly appreciate any pointers to help fix the issue.

Jitsi Web Logs:
```
"GET /xmpp-websocket?room=test HTTP/1.1" 403 284 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
```
Chrome screenshot
![image](https://user-images.githubusercontent.com/3583526/143402494-04c819d1-e64c-47e9-a3bf-6cc479dc09f1.png)

**Comment by vkruoso** [comment]
@saghul I'm upgrading my stack version from a very old one and are now facing the same issue with the websocket. 403 logs in the nginx side, nothing in the prosody container. Any points?

Accessing directly via HTTP gives the prosody message "It works! Now point your WebSocket client to this URL to connect to Prosody.", so that adds to the confusion.

**Comment by saghul** [comment]
Do you have PUBLIC_URL set?

**Comment by vkruoso** [comment]
Yes. The connection address seems to be the right one. If I just change it to`https` instead of `wss` it shows the message above.

**Comment by saghul** [comment]
PUBLIC_URL should be an HTTPS link, the WS URL is generated internally.

**Comment by vkruoso** [comment]
Yes, correct. The PUBLIC URL is the "https://\<myaddress\>.com". What I meant was that the address the browser is trying to connect is correct. Also, the config in the web NGINX is also correct:

```
# xmpp websockets
location = /xmpp-websocket {
    proxy_pass http://prosody:5280/xmpp-websocket;
    proxy_http_version 1.1;

    proxy_set_header Connection "upgrade";
    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Host meet-leads2b;
    proxy_set_header X-Forwarded-For $remote_addr;
    tcp_nodelay on;
} 
```

From the web container, getting the prosody address:
```
<!DOCTYPE html><html><head><title>Websocket</title></head><body>
                        <p>It works! Now point your WebSocket client to this URL to connect to Prosody.</p>
                        </body></html>
```
That show that the web container can correctly communicate with prosody.

But somehow when accessing from outside nginx shows 403 in the logs and prosody shows nothing. 

Is there any way to enable debugging in prosody so we can check if stuff is reaching it?

**Comment by saghul** [comment]
> Is there any way to enable debugging in prosody so we can check if stuff is reaching it?

You can enter the container and inspect it I guess.

Can you check in the network tab who is replying with that 403?

**Comment by vkruoso** [comment]
Hi @saghul ! It was the nginx container that were responding with 403.

I've solved this but I'm not sure why. The cluster was on GCP when this happened, so there could be something with the network there, or it might just be some variable I've missed before. I've moved to AWS and things worked without much change. Also, the colibri websocket was a challenge: I was having issues with low quality streams and it turns out the `colibri-ws` is essential for the negotiation of those stream qualities, so my mistake was the JVB_WS_SERVER_ID, that needed to be a hostname / ip internally accessible of the JVB.

Thanks for your pointers!

**Comment by saghul** [comment]
Right. This setup is designed to work by default, as is, in a single host compose setup. Anything that deviates from that may require tweaking. I don't think there is a way to have a default configuration that works for every possible environment.
