### ISSUE TITLE
Affected from CVE-2021-44228 ?

### ISSUE THREAD

**Issue by mungo312** [jitsi/docker-jitsi-meet#1162]
Hi everybody,

are the version provided in the latest tag vulnerable for CVE-2021-44228 ?
According to https://github.com/jitsi/jitsi-videobridge/issues/1773 the jvb container at least is affected.
Can you provide images not vulnerable ?

**Comment by saghul** [comment]
As you've seen on the linked issue we are working on it.

**Comment by mungo312** [comment]
If I understand the Updates correctly, all versions from stable-5870 and newer, are not affected, correct ? @saghul  Can you confirm this ?
Is there any document or trick which shows which component version is used in which release ?

You have all done a great job. You reacted way better than for example VMware. 
Thank you !

**Comment by damencho** [comment]
> If I understand the updates correctly, all versions from stable-5870 and newer, are not affected, correct ? @saghul Can you confirm this ?

It is stable-5963 and newer.

**Comment by bgrozev** [comment]
> Is there any document or trick to see which component version is used in which release ?

Look for git tags in the individual repository, e.g. https://github.com/jitsi/jitsi-videobridge/releases/tag/stable%2Fjitsi-meet_5963

**Comment by saghul** [comment]
https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-6726 is out. You can read more about how the vulnerability affected the Jitsi components here: https://community.jitsi.org/t/cve-2021-44228-and-jitsi-components/108844

The default Docker setup is unafected because there is no way to enable CallStats in the backends.

**Comment by d-Rickyy-b** [comment]
I just want to leave the strings log4j and log4shell here, so this can be found when searching issues for these strings. Thanks for your work!

**Comment by mhow2** [comment]
@saghul : thank you for the work. If I understand correctly, the release `6726` does not relate with the current CVE isn't ?

**Comment by saghul** [comment]
That release does include an updated version of the JVB, which wouldn't expose you to the vulnerability even if you had Callstats enabled on the JVB.

**Comment by waja** [comment]
It turns out that the fix in 2.15.0 is not fixing the issue completely: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046

**Comment by bgrozev** [comment]
CVE-2021-45046 does not affect jitsi-videobridge or jigasi , because they don't use any of the related features in PatternLayout ([jvb](https://github.com/jitsi/jitsi-videobridge/blob/master/config/log4j2.xml#L9), [jigasi](https://github.com/jitsi/jigasi/blob/master/jigasi-home/log4j2.xml#L9)). We're in the process of updating to 2.16.0 in any case.
