### ISSUE TITLE
CVE-2021-45046: Fix for CVE-2021-44228 (log4j 2.15.0) didn't fix it

### ISSUE THREAD

**Issue by waja** [jitsi/docker-jitsi-meet#1173]
I guess #1162 was just the first step ... https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046.

TL;DR: log4j 2.16 stripped out the problem by `removing support for message lookup patterns and disabling JNDI functionality by default`.

**Comment by saghul** [comment]
Thanks for the heads up.

**Comment by bgrozev** [comment]
Please note that CVE-2021-45046 is separate and does not have the same implications as CVE-2021-44228. 

CVE-2021-45046 does not affect jitsi-videobridge or jigasi , because they don't use any of the related features in PatternLayout ([jvb](https://github.com/jitsi/jitsi-videobridge/blob/master/config/log4j2.xml#L9), [jigasi](https://github.com/jitsi/jigasi/blob/master/jigasi-home/log4j2.xml#L9)). We're in the process of updating to 2.16.0 in any case.

**Comment by luisfelipe3d** [comment]
any update?

**Comment by luisfelipe3d** [comment]
> We removed log4j from jitsi-videobridge and jigasi master.

Has this update been released?

**Comment by jan-di-cgm** [comment]
Dear sender

due to a ransomware attack and necessary security measures, CGM is temporarily not reachable via the usual eMail addresses and Office phone numbers.
Please feel free to use SMS and mobile telephony to contact us.

Thank you for your understanding and best regards, your CGM Team

-----------------

Sehr geehrte Absenderin,
sehr geehrter Absender,

aufgrund einer Ransomware-Attacke und notwendiger Sicherheitsmaßnahmen, ist CGM vorübergehend nicht über die gewohnten eMail-Adressen und Festnetznummern erreichbar.
Bitte nutzen Sie gerne SMS und Mobilfunk-Telefonie, um mit uns Kontakt aufzunehmen.

Vielen Dank für Ihr Verständnis und freundliche Grüße, Ihr CGM-Team

**Comment by luisfelipe3d** [comment]
User reported!

**Comment by mnoji** [comment]
Hi, Do you have any update?
We want to start to use Jitsi and are waiting for fix this issue.

**Comment by saghul** [comment]
The latest stable contains no log4j at all.
