### ISSUE TITLE
Prosody build failed on 7001 and using 0.11.13-1~bpo11+1 as prosody version

### ISSUE THREAD

**Issue by denis-ionov** [jitsi/docker-jitsi-meet#1259]
Building on 7001 and patching prosody Dockerfile to use 0.11.13-1~bpo11+1 as prosody version (fix from master branch). Yesterday build was always success. Today got error `E: Version '0.11.13-1~bpo11+1' for 'prosody' was not found` on build

**Comment by saghul** [comment]
Check what Prosody version made it to Debian backports.

**Comment by saghul** [comment]
Damn, that's bad, because there are incompatibilities with 0.12 and our stable release. You also can't use the prosody-0.11 package from upstream because we added support for it after the stable release was cut.

So I'm afraid you're in a tough spot.

You can either use the unstable release which is currently using 0.11 just fine, or use our stable images, which you can't rebuild right now :-/

**Comment by denis-ionov** [comment]
@saghul i see that incompatibility is all about muc_owner_allow_kick.patch. I'm try to comment it out from prosody Dockerfile and build on 0.12

**Comment by saghul** [comment]
There is more than that. Jicofo also needs to be updated beyond stable.

**Comment by denis-ionov** [comment]
> You can either use the unstable release which is currently using 0.11 just fine
No, i can't. As i mentioned in first comment, when i try build from master, i got error `E: Version '0.11.13-1~bpo11+1' for 'prosody' was not found`

**Comment by saghul** [comment]
Oh, looks like I forgot to push the patch 🤦‍♀️ 

Change the prosody package to "prosody-0.11" no quotes.

That will install the latest version in the 0.11 series. Then you should be able to rebuild.

**Comment by denis-ionov** [comment]
@saghul thanks for the help! Now build works

**Comment by Vitaliy86** [comment]
Prosody 0.12.6 released
