### ISSUE TITLE
Completely bizarre as a docker install

### ISSUE THREAD

**Issue by sjatkins** [jitsi/docker-jitsi-meet#1268]
The instructions include install of several packages that could be part of the dockerfile[s] themselves.  Why is it like this?  And there are no dockers to pull from normal public repos or even private ones.  It looks more like a kit to use to build dockers than ready to run docker to me.  Am I missing something?

**Comment by saghul** [comment]
What packages are you talking about?

All our images are on DockerHub: https://hub.docker.com/u/jitsi/

You can either pull them individually (not recommended) or grab a stable release compose file and do they will be pulled automatically when you start.

The point of the install is to get a compose file which has references to stable images, since mixing them may result in incompatibilities.

This is not a single container setup, multiple containers are needed, with specific versions.

Do you have any specific suggestions on how to improve this?

**Comment by Wobwobwob** [comment]
Hey and thanks for the work you're doing.

I think the main surprise when using docker-jitsi-meet is that usually we'd have a docker-compose file pointing at a tag "latest" so that we get updates when pulling the latest image. In docker-jitsi-meet we have to watch out for now stable releases on Github and then download the latest docker-compose file. This doesn't integrate well with other docker projects workflows, so it will most likely be forgotten.

One idea to solve this: Provide a "stable" tag in the docker images. Each image sets "stable" to the image specified in the docker-compose file of the latest stable Github release. Then, you could have the stable Github release point each image at it's "stable" version and only update those (not the docker-compose file). 

This would allow us to pull the latest docker-jitsi-meet version directly from docker, without having to check Github.

**Comment by saghul** [comment]
> I think the main surprise when using docker-jitsi-meet is that usually we'd have a docker-compose file pointing at a tag "latest" so that we get updates when pulling the latest image. In docker-jitsi-meet we have to watch out for now stable releases on Github and then download the latest docker-compose file. This doesn't integrate well with other docker projects workflows, so it will most likely be forgotten.

We tried that, didn't work so well. We are not yet ready for that. The problem with that approach is that is that if a new stable release adds support for some env variables and you don't update your compose file, they won't be passed around so you'll be wondering why if you have added them to your .env file. This is not a theoretical problem I'm thinking about, this was a problem in the past which was fixed by tagging images in the compose file.

> One idea to solve this: Provide a "stable" tag in the docker images.

This is not a bad idea and it's analogous to our `unstable` tag, so I just pushed it.

> Each image sets "stable" to the image specified in the docker-compose file of the latest stable Github release. Then, you could have the stable Github release point each image at it's "stable" version and only update those (not the docker-compose file).

Not quite. Before the last release I added a way to override the compose file image versions right from .env: https://github.com/jitsi/docker-jitsi-meet/commit/1463df4c09b4734f3a3d56338ddf3754d85d7e6c so you could set the version to `stable` there. Note that you'd still run into issues if you are trying to use new env variables.

> This would allow us to pull the latest docker-jitsi-meet version directly from docker, without having to check Github.

I think we are in a better position than a couple of years ago (specially after the last release where I replaced most of the settings with defaults) but I'd still consider risky to mindlessly update to a new version.
