### ISSUE TITLE
ICE with NAT and DOCKER_HOST_ADDRESS

### ISSUE THREAD

**Issue by praet0ri4n** [jitsi/docker-jitsi-meet#171]
Hi devs,

sorry for re-opening discussion about closed issues from other users, but it may be helpful for future questions maybe.
I am struggling to understand for which address the DOCKER_HOST_ADDRESS is standing for. As you have the docker internal IP, something like 172.22..., you also have a LAN ip, e.g. 192.168... and then you also have your PUBLIC ip visible from outside.

As I understood from this explanation here
https://github.com/jitsi/docker-jitsi-meet/issues/137
if I am running a docker jitsi instance on my LAN and portforwarding UDP 10000 through my router, I should be setting DOCKER_HOST_ADDRESS to my public IP?
Or is this ALWAYS  the local LAN IP, to let the docker container know, what the host address is?

I did set DOCKER_HOST_ADDRESS=My public ip and started the containers via docker-compose. Everything goes up without issues. I can go to my meet. webpage, initiate a conference, connect other users to it either through web or the android apps, everybody can hear and see others. But If I check the tcpdump and especially the UDP traffic on my server, it is pretty busy relaying all the media between users. I then tried to connect two android phones via 3g network only and even in that case the media is getting relayed. Is this relay ok?

So my final question. Is this the final state as it should be? I expected that the users end up sending media directly to each other to addresses found by ICE and that the server is offloaded then.
Or does the UDP traffic on the server only say, that there is still something to be checked to make ICE work.

I did experiment a bit with the ~/.jitsi-meet-cfg/jvb/sip-communicator.properties and set
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=172.22.0.10 (the jvb container IP address) AND
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=my public IP
and removed the STUN servers..
In this scenario I get the two android phones talking directly to each other, but I can't connect any other device from behind other NAT's - all the screens go dark.

What I am trying to accomplish is to not to have the server relaying all the media. Otherwise it will be slowing down other web services running there.

Maybe I am expecting something to work in a way it was not meant to..
Please correct and clarify.

Thank you much for your awesome work.

**Comment by saghul** [comment]
The setting is meant to allow the user to decide which is the "advertised public address". This is the Docker host's adress almost always, except on setups where LAN-only communication is desired. On hindsight #137 was right, the name is not great. Also, there are ways to detect the public IP which we could use.

I'll try to improve this when I get some time.

> I did set DOCKER_HOST_ADDRESS=My public ip and started the containers via docker-compose. Everything goes up without issues. I can go to my meet. webpage, initiate a conference, connect other users to it either through web or the android apps, everybody can hear and see others. But If I check the tcpdump and especially the UDP traffic on my server, it is pretty busy relaying all the media between users. I then tried to connect two android phones via 3g network only and even in that case the media is getting relayed. Is this relay ok?

Yes, this is normal.



> I did experiment a bit with the ~/.jitsi-meet-cfg/jvb/sip-communicator.properties and set
> org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=172.22.0.10 (the jvb container IP address)

That's always wrong, since other clients connecting to your server will never be able to access that IP.

> In this scenario I get the two android phones talking directly to each other, but I can't connect any other device from behind other NAT's - all the screens go dark.

That's most likely because when 2 devices are in the room they will conect directly (p2p) instead of via the JVB.

> What I am trying to accomplish is to not to have the server relaying all the media. Otherwise it will be slowing down other web services running there.

Jitsi will always relay the media when there are > 2 participants in a room. For the 2 participants case, we have special handling, but it will only work if there are is a direct connection path. There is a way to make sure this is always the case: by using a TURN server, which will act as the relay as needed, but this setup doesn't include that yet, we'll have it hopefully soon.

**Comment by praet0ri4n** [comment]
Thanks alot for yor response and your support. I know from setting up Asterisk/Kamailio things in the past how difficult that is to make ICE work, thus my digging around :) Looking forward for next versions!

**Comment by Integrion** [comment]
Hi everyone, 

We cloned the Jitsi-meet docker-compose bundle, configured the .env file and then  ran docker-compose up -d, and lo and hold, the all relevant containers appear to be running, but nothing, including the web interface, is reachable.  

Specifically we did not set the Docker_Host_Address to our public IP address, since this setup is NOT running behind a NAT firewall or on a LAN.  Is this not correct?

Also, once one has initially run Docker-Compose up, what is the proper way to make changes to one's .env settings so that they are properly reflected if Docker-Compose up does not regenerate all configuration files upon container restart?

Thanks,
JC

**Comment by bilalshahzad139** [comment]
> Hi everyone,
> 
> We cloned the Jitsi-meet docker-compose bundle, configured the .env file and then ran docker-compose up -d, and lo and hold, all relevant containers appear to be running, but nothing, including the web interface, is reachable.
> 
> Specifically we did not set the Docker_Host_Address to our public IP address, since this setup is NOT running behind a NAT firewall or on a LAN. Is this not correct?
> 
> Also, once one has initially run Docker-Compose up, what is the proper way to make changes to one's .env settings so that they are properly reflected if Docker-Compose up does not regenerate all configuration files upon container restart?
> 
> Thanks,
> JC

You may have to enable ports in firewall if your web is still not reachable after running containers https://github.com/jitsi/docker-jitsi-meet#external-ports

If you make any change in .env file, you need to stop by using 'docker-compose stop' command and then run again by using docker-compose command.
