### ISSUE TITLE
Jibri in docker container doesn't work

### ISSUE THREAD

**Issue by volo-zyko** [jitsi/docker-jitsi-meet#174]
This is the same issue as jitsi/jibri#231. Chrome inside the container tries to open "https://meet.jitsi" while should be directed to "https://external.fqdn".

Proposed in the above issue solution probably should work. Related code is https://github.com/jitsi/jibri/blob/d566436459b5c1f1772af550d5d4c3357ceb2cee/src/main/kotlin/org/jitsi/jibri/api/xmpp/XmppApi.kt#L276 but it's not completely clear how to preserve the old behavior. In some setups it will need to use "external.fqdn" and in some setups - `xmpp_domain` (which proably will be the same as "external.fqdn").

**Comment by saghul** [comment]
Are you using the latest version of the images? When I tested it before merging it did work. Can you share your `.env` file?

**Comment by volo-zyko** [comment]
I have the latest images.

Here is [`.env`](https://gist.github.com/volo-zyko/18e458e0d552c8fcf41d5adc69c75167) file.

**Comment by saghul** [comment]
I don't see any obvious mistake. I'll try to repro and let you know.

**Comment by netaskd** [comment]
@volo-zyko 
> Chrome inside the container tries to open "https://meet.jitsi" while should be directed to "https://external.fqdn".

For get properly direct to external.fqdn you have to set `XMPP_DOMAIN=external.fqdn` and so on, because  
https://github.com/jitsi/docker-jitsi-meet/blob/6234a18dc69e81ff01cb52a5dc89534ee4f93273/env.example#L281

original in config.json: https://github.com/jitsi/jibri/blob/d566436459b5c1f1772af550d5d4c3357ceb2cee/resources/debian-package/etc/jitsi/jibri/config.json#L49

**Comment by volo-zyko** [comment]
After some more thinking about this problem I changed all `jitsi.meet` strings in the above `.env` file to `external.fqdn`. Also, I changed `LDAP_FILTER` to `(|(mail=%U@external.fqdn)(mail=%U@external.fqdn2))` (thanks to the suggestion in  jitsi/docker-jitsi-meet#173). Now, I can login with the full email from domain `external.fqdn` and users in `external.fqdn2` can only login with `@external.fqdn2` omitted.

Still Jibri cannot record video. I can see in logs that chrome tries to open `https://external.fqdn` which is wrong and should be `https://video-chat.external.fqdn`.

**Comment by volo-zyko** [comment]
@netaskd 
> For get properly direct to external.fqdn you have to set XMPP_DOMAIN=external.fqdn and so on

Thanks again for the suggestion. It takes time for me to grasp all these things. I'm feeling lack of documentation.

So, I changed everything again, now `meet.jitsi` to `video-chat.external.fqdn`. This time chrome attempts to open `https://video-chat.external.fqdn` as it should but I still get `ERR_CONNECTION_REFUSED` in chrome. However, this time it was easy. Since I deploy with docker-jitsi-meet then inside Jibri container `video-chat.external.fqdn` resolves to the local address of the Jitsi container and since I manage SSL certificates outside of Jitsi setup (i.e. in containers all traffic is plain http) chrome naturally cannot load from https. I think I can send a PR to docker-jitsi-meet.

**Comment by Rikhart** [comment]
I have the same error, I can´t  show recording button my container is running but, I don't know why options dont show in a frontend.

How I can solve this problem?

**Comment by shubham2110** [comment]
I found the actual issue here.. 

If ServerHost is different from XMPP host Jibri won't work at all.


in the function getCallUrlInfoFromJid it is giving url with http://$xmppDomain but it should have been giving url with http://xmppServerHosts

Could anyone in jibri Developers please check it.

@saghul
@netaskd

**Comment by shubham2110** [comment]
@netaskd

What I did,  I Hardcoded my external server URL in file XmppUtils.kt 
It worked for me. 

Try it with yours too. 

@saghul Please check function getCallUrlInfoFromJid  inside XmppUtils.kt and return URL with one of xmppServerHost rather than xmppDomain 

I know it may  break multiple host thing.. 

Other way would be to call all urls with all hosts and start session with first successful URL.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/pull/1046
