### ISSUE TITLE
maybe see if you can switch to alpine linux?

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/docker-jitsi-meet#253]
maybe see if you can switch to alpine linux? Would save quite a few 100's of MB's.

**Comment by sapkra** [comment]
I think the reason we are using debian is that prosody and all the other programs are published to debian repositories. In my opinion it would be the best if we would use quarkus, so that the java applications (e.g. nearly all parts of jitsi) would be native binaries.

https://quarkus.io/

**Comment by saghul** [comment]
@f1-outsourcing  We develop and deploy exclusively on Debian based distros. This is the only flavor we intend to support in this setup, since we cannot guarantee the stability of things we simply don't use. You are welcome to built images using Alpine, but we won't be using those in this project, sorry.

@sapkra I think we still depend on OpenSSL and usrSCTP for example, and that seems unlikely to change...
