### ISSUE TITLE
Resource required

### ISSUE THREAD

**Issue by Dextroz** [jitsi/docker-jitsi-meet#260]
How resource demanding is Jitsi to run.

Like what is minimum/recommended specs to run Jitsi?

**Comment by saghul** [comment]
It depends on many factors, please open a discussion topic in the community forum: https://community.jitsi.org/

**Comment by sapkra** [comment]
I think this should be part of a README. Because it's no discussion topic but a documentation topic instead it should not be in the community forum In my opinion.

I've encountered very often that I have to google for specific stuff about jitsi which should be documented and even had to look in the code multiple times. So this small thing should really be in something like a README file.
The docs of jitsi have a huge potential to be improved and are in my opinion the most problematic topic of the project. (no offense but e.g. I tried to document some stuff and my PRs are approved but not merged since July last year)

The jitsi core team is pretty small for this huge project I guess. So maybe the community could be more involved somehow - maybe by setting up a documentation repository by using GitBook or something else so that external jitsi experts could manage this repository and maybe also be able to review code changes later on.

It's definitely a huge topic and not the right place to discuss it. This discussion may be perfect for the community forum. 😉
