### ISSUE TITLE
Update dev branch

### ISSUE THREAD

**Issue by sapkra** [jitsi/docker-jitsi-meet#271]
@saghul I've noticed that some commits are existing in the current master but missing in the dev branch. I think the master branch should be merged into the dev branch but I was not able to create a pull request - an error occurred.

**Comment by saghul** [comment]
This is a nice opportunity to say that we are dropping the dev branch. We are going to try and deliver more frequent updates, and since the REAME is served off master, it makes sense for people to arrive at what they can run. I won't ddelete the branch, but let's give this a go and see where we land.

**Comment by sapkra** [comment]
Ok but then we should merge the dev branch into the master branch. ;) There is still one commit which has not land in master yet.

**Comment by saghul** [comment]
Which one? I did merge dev into master today.

**Comment by sapkra** [comment]
This one: 29125fd40dfe8186d8ee5cff18e42d5afb06d33d

**Comment by saghul** [comment]
Ah my bad I merged it after merging dev, will fix!
