### ISSUE TITLE
ENABLE_GUESTS is not working for me

### ISSUE THREAD

**Issue by roycec** [jitsi/docker-jitsi-meet#337]
I'm trying to set up a dedicated Jitsi Meet server on docker. The setup worked so far. But I tried to set the ENABLE_GUESTS=1, so that guests can join a meeting resp. only have to enter a meeting password. But everytime I try to connect from a second device, I'm always prompted for username and password (ENABLE_AUTH=1 is also set). What do I do wrong here? I already deleted the .jitsi-meet-cfg/jicofo directory (is this enough?) and restarted all containers.

**Comment by saghul** [comment]
Not enough, wipe the entire CONFIG volume. web and prosody also need config changes.

**Comment by bkraul** [comment]
For me is the opposite. I have both `ENABLE_AUTH=` and `ENABLE_GUESTS=1` with ldap auth. In the past, the first person to enter the meeting would get a password prompt, and subsequent guests would not. This is the expected behavior. However, now, even with those 2 vars, everyone gets moderator rights. Seems might be related to #285 .

I have deleted EVERY volume, and images. No avail.

**Comment by wilypomegranate** [comment]
This doesn't work on the kubernetes example. I get the behaviour described in the issue description. ENABLE_GUESTS="1" on all the images doesn't seem to work and I get the auth popup for guests after the room is created.
