### ISSUE TITLE
Account creation/modification not supported.

### ISSUE THREAD

**Issue by gs4711** [jitsi/docker-jitsi-meet#443]
Here is the command sequence which leads to this error:

```
server# docker-compose exec prosody /bin/bash
root@df3ccd829902:/# prosodyctl --config /config/prosody.cfg.lua register TheDesiredUsername meet.jitsi TheDesiredPassword
Error: Account creation/modification not supported.
```

The configuration had been adapted as described within the README
```
server# egrep '(AUTH_TYPE|ENABLE_AUTH)' .env
ENABLE_AUTH=1
AUTH_TYPE=internal
```

**Comment by saghul** [comment]
What version of the images are you using?

**Comment by gs4711** [comment]
Just fetched onto a CentOS hosts:
```
# docker image ls
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
jitsi/jvb            latest              680791a70f08        6 days ago          270MB
jitsi/jicofo         latest              7d03c2568c0f        6 days ago          270MB
jitsi/prosody        latest              2cf18434c32a        6 days ago          249MB
jitsi/web            latest              05675e6749f0        6 days ago          259MB

```

**Comment by tbendiksen** [comment]
Same issue, same config, same images except running Debian Buster on the host.

**Comment by gs4711** [comment]
Sorry, does not solve the problem:

[root@server]# docker-compose down
Stopping dockerjitsimeet_jicofo_1  ... done
Stopping dockerjitsimeet_jvb_1     ... done
Stopping dockerjitsimeet_prosody_1 ... done
Stopping dockerjitsimeet_web_1     ... done
Removing dockerjitsimeet_jicofo_1  ... done
Removing dockerjitsimeet_jvb_1     ... done
Removing dockerjitsimeet_prosody_1 ... done
Removing dockerjitsimeet_web_1     ... done
Removing network dockerjitsimeet_meet.jitsi

[root@server]# rm -rf ~/.jitsi-meet-cfg/

[root@server]# docker-compose up -d

[root@server]# docker-compose exec prosody /bin/bash

root@3b0917e6857b:/# prosodyctl --config /config/prosody.cfg.lua register TheDesiredUsername meet.jitsi TheDesiredPassword
Error: Account creation/modification not supported.
root@3b0917e6857b:/# 

Same behaviour as earlier stated.

**Comment by saghul** [comment]
Please pull the latest images before starting again.

**Comment by gs4711** [comment]
Thanks, @saghul !

Now I can confirm that the latest images work fine!!!

**Comment by xhsiung** [comment]
hi gs4711
how did you confirm that the latest images ?

**Comment by gs4711** [comment]
Taking those commands 

```
        mkdir /root/projects
        cd /root/projects;
        rm -rf  docker-jitsi-meet
        git clone https://github.com/jitsi/docker-jitsi-meet
        cd docker-jitsi-meet
        cp    env.example  .env
        vi .env
        ./gen-passwords.sh
        mkdir -p /root/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb,jigasi,jibri}
        docker-compose up -d
        docker-compose exec prosody prosodyctl --config /config/prosody.cfg.lua register USER meet.jitsi PASSWORD
        docker container ls

```
as described within the README have led to a well-working environment with login-protected room creation.

**Comment by thieman** [comment]
I've just installed Jitsi for the very first time today and I'm still having this problem. I went through the same procedure as @gs4711 did to clean out my config dir after updating .env. I'm getting `Error: Account creation/modification not supported.` from prosody and the web client isn't demanding authentication anywhere.

```
root@bastion:~/config/jitsi# egrep '(AUTH_TYPE|ENABLE_AUTH)' .env
ENABLE_AUTH=1
AUTH_TYPE=internal
```

**Comment by saghul** [comment]
If you already have old images downloaded you might want to do `docker-compose pull` before the up.

**Comment by m90** [comment]
I am running into the same issues, but even after following all of the above advice (wiping the config files and volumes, pulling the latest images as of today) I am still seeing that 

```
Error: Account creation/modification not supported.
```

message. Is there any other thing I could do to further debug this?

This is what I am running:

```
root@offen-meet:~/docker-jitsi-meet# docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED              STATUS              PORTS                                              NAMES
b90db9631178        jitsi/jvb:latest       "/init"             About a minute ago   Up About a minute   0.0.0.0:4443->4443/tcp, 0.0.0.0:10000->10000/udp   docker-jitsi-meet_jvb_1
7c0a03510058        jitsi/jicofo:latest    "/init"             About a minute ago   Up About a minute                                                      docker-jitsi-meet_jicofo_1
364adbe46617        jitsi/web:latest       "/init"             About a minute ago   Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp           docker-jitsi-meet_web_1
853980f587bd        jitsi/prosody:latest   "/init"             About a minute ago   Up About a minute   5222/tcp, 5269/tcp, 5280/tcp, 5347/tcp             docker-jitsi-meet_prosody_1
root@offen-meet:~/docker-jitsi-meet# docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jitsi/jvb           latest              ff366d6653e3        2 weeks ago         278MB
jitsi/jicofo        latest              8a99d30ab075        2 weeks ago         292MB
jitsi/prosody       latest              50f5c1e719aa        2 weeks ago         106MB
jitsi/web           latest              7de9a63e7e82        2 weeks ago         483MB
```

**Comment by robots4life** [comment]
@m90 I can confirm @gs4711 's solution https://github.com/jitsi/docker-jitsi-meet/issues/443#issuecomment-613472316 works however without running `rm -rf  docker-jitsi-meet` since I made a new folder and did not have anything in it.

To clean the server of old images and containers run `docker system prune -a`.
This should remove all images and containers and networks.
Make sure any Jitsi leftover config folders, files are also deleted.
I started with a fresh untouched server instance to make sure.

For me the important bit was also to make a folder, **inside** that download the docker-jitsi-meet repo with `git clone https://github.com/jitsi/docker-jitsi-meet` and then, right at the beginning for the first run have the following options in the `.env` file enabled as well as firewall rules setup correctly.

So make a copy of the `env.example` file and have these values added into it, the rest is up to you, or just leave those on default settings.

```
#
# Basic configuration options
#

# Directory where all configuration will be stored
CONFIG=~/.jitsi-meet-cfg

# Exposed HTTP port
HTTP_PORT=80

# Exposed HTTPS port
HTTPS_PORT=443

# System time zone
TZ=UTC

# Public URL for the web service
PUBLIC_URL=https://your.public.url.com

#
# Let's Encrypt configuration
#

# Enable Let's Encrypt certificate generation
ENABLE_LETSENCRYPT=1

# Domain for which to generate the certificate
LETSENCRYPT_DOMAIN=your.public.url.com

# E-Mail for receiving important account notifications (mandatory)
LETSENCRYPT_EMAIL=certbot@some_real_email.com

# Enable authentication
ENABLE_AUTH=1

# Enable guest access
ENABLE_GUESTS=1

# Select authentication type: internal, jwt or ldap
AUTH_TYPE=internal

# Redirect HTTP traffic to HTTPS
# Necessary for Let's Encrypt, relies on standard HTTPS port (443)
#ENABLE_HTTP_REDIRECT=1
# I did NOT have the option enabled since port 443 is open on the firewall and
# Let's Encrypt can access the service there. However you might want to enable
# this rule if this do not work for you.
# It should work without this rule enabled though.
```
Once you have those in place in the `.env` file run the `./gen-passwords.sh` command inside the repo folder, so inside `/jitsi-project/docker-jitsi-meet` for example.

On the server then have the following ufw firewall rules set.
```
Status: active

To                         Action      From
--                         ------      ----
80/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
your_ssh_port/tcp     ALLOW       Anywhere                  
10000/udp                  ALLOW       Anywhere                  
4443/tcp                   ALLOW       Anywhere                  
80/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
your_ssh_port/tcp (v6)  ALLOW       Anywhere (v6)             
10000/udp (v6)             ALLOW       Anywhere (v6)             
4443/tcp (v6)              ALLOW       Anywhere (v6)      
```
Once you have that in place run `docker-compose up` and make sure everything runs fine. Check the log. At this stage you don't have a user and pass but can verify Let's Encrypt made a cert for  `your.public.url.com`. Visit `https://your.public.url.com` and see the console for the traffic.

Hit `ctrl + c` to stop those services and exit this live running mode.

Then run `docker-compose up -d` to run the Jitsi services in detached mode.

With `docker ps` now check that you have a container running with name `docker-jitsi-meet_prosody_1`.

Now, while the services are running in detached mode run the command to make create a "host" with username and password.

`docker-compose exec prosody prosodyctl --config /config/prosody.cfg.lua register username  meet.jitsi password`.

If you see no error then the user and password have been created for a "host".

Now stop all containers and services.
For that I use `docker stop $(docker ps -a -q)`.

Last not least `docker-compose up -d` again to start all services in detached mode.

Go to `https://your.public.url.com` now.
Make a room.
Enter the room.
Now a modal should come up asking you if you are the "host", confirm and in the next modal enter the username and password from the command above.

That is it, anonymous guests now join this room, with or without password, depending on how you setup the room by clicking on the "i" info icon bottom right.

Now when you go back to `https://your.public.url.com` in a new incognito tab you can create a new room, however you will not get past the "host" modal that pops up since an anonymous user cannot create more rooms, in fact anyone that does not have the username and password cannot create more rooms.

However the created room by anon will show up in the list of rooms under `https://your.public.url.com`.
But don't concern yourself with that, `https://your.public.url.com` is now protected and only the "host" can create more rooms.
Could tweak the Nginx conf a bit to provide a username and password for `https://your.public.url.com` but that is for another time.

**Comment by j2l** [comment]
I also have the problem.
From within the container, if I try to create a user from config/ it seems more verbose:
```
root@2f48e9cb4dc6:/config# ls
certs  conf.d  data  prosody.cfg.lua  saslauthd.conf
root@2f48e9cb4dc6:/config# prosodyctl --config prosody.cfg.lua register USER meet.jitsi PASSWORD


**************************
A problem occurred while reading the config file prosody.cfg.lua

Error: /usr/lib/prosody/core/configmanager.lua:185: cannot open /conf.d: No such file or directory

More help on configuring Prosody can be found at https://prosody.im/doc/configure
Good luck!
**************************
```

**Comment by umerf52** [comment]
> 
> 
> I also have the problem. On docker version, 5142.
> 
> From within the container, if I try to create a user from config/ it seems more verbose:
> 
> ```
> root@2f48e9cb4dc6:/config# ls
> certs  conf.d  data  prosody.cfg.lua  saslauthd.conf
> root@2f48e9cb4dc6:/config# prosodyctl --config prosody.cfg.lua register USER meet.jitsi PASSWORD
> 
> 
> **************************
> A problem occurred while reading the config file prosody.cfg.lua
> 
> Error: /usr/lib/prosody/core/configmanager.lua:185: cannot open /conf.d: No such file or directory
> 
> More help on configuring Prosody can be found at https://prosody.im/doc/configure
> Good luck!
> **************************
> root@2f48e9cb4dc6:/config# prosodyctl --help
> 
> 
> **************************
> Prosody was unable to find the configuration file.
> We looked for: /etc/prosody/prosody.cfg.lua
> A sample config file is included in the Prosody download called prosody.cfg.lua.dist
> Copy or rename it to prosody.cfg.lua and edit as necessary.
> More help on configuring Prosody can be found at https://prosody.im/doc/configure
> Good luck!
> **************************
> ```
> 
> Indeed, no /etc/prosody/

Hey were you figure out the issue?

**Comment by j2l** [comment]
Nope.
Sadly, it looks like no help will come on this one.
