### ISSUE TITLE
Wrong /tmp rights prevent container update, here's the fix :)

### ISSUE THREAD

**Issue by j2l** [jitsi/docker-jitsi-meet#464]
First of all, thank you Jitsi-Meet team (same as 8x8?)!
This project is wonderful.
And wonderfully complex.

I spent quite some time and sweat on it and noticed a few glitches (https://community.jitsi.org/t/3-ways-conf-on-docker-was-working-last-week-stopped-after-unknown-changes/34748, BTW, I can't change my title to [solved])

One easily fixed is the ability to update a container, actually if you run `apt update`, you get multiple errors like:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.debian.org/debian stretch-updates InRelease: Couldn't create temporary file /tmp/apt.conf.Iky6el for passing config to apt-key
```
that's because /tmp is 700, `ls -ld /tmp`
`drwxr-xr-t 1 root root 4096 Apr 16 16:17 /tmp`
Once you `chmod 777 /tmp`, `apt update` will pass and apt upgrade too with new jitsi updates.

Hope it helps :smile_cat:

**Comment by saghul** [comment]
Can you propose a patch to the base container?

**Comment by sapkra** [comment]
@j2l So you want to run `apt update` and `apt upgrade` while the container is running? I don't quite understand why this should be necessary? That's not how docker is intended to be used.
But perhaps I misunderstand you.

**Comment by j2l** [comment]
@sapkra, yes.
I don't know the procedure to upgrade Jitsi-docker, can you please point me to one?
If you just delete the image to get the latest, you may get a conflict between your web/ content and the new image, right?
If no, and you keep your current config files, what happens if update caters new stuff in config.js, interface_config.js? You won't see them, right?
Same for people who have [custom UI](https://github.com/jitsi/docker-jitsi-meet/issues/327).

Upgrading the container and making an image from it might be one of the solution. I'm open to other points of view.

**Comment by sapkra** [comment]
If you want to update jitsi to a newer version you have to pull the new images. They are also tagged with the new jitsi version. Additionally all containers have the same version which are compatible with each other.
I prefer generating the config files on each container start so that you will not have this problem you mentioned. To do that you can just remove the config volumes from the containers. If you have a custom UI you are responsible to update the config of these yourself anyway.

If you run apt commands in a running container everything will be reseted after you restarted the container. If you really want to use the docker images you have to know the docker basics in my opinion. Maybe it's better if you would use the debian packages directly on your machine.

**Comment by saghul** [comment]
Agreed with Paul here.

**Comment by j2l** [comment]
> If you really want to use the docker images you have to know the docker basics in my opinion.
Not really friendly in my opinion. I don't get why you thought you needed to say this.
Especially since I already explained you can build an image from a running (and updated) container.

**Comment by saghul** [comment]
I don't think Paul was trying to be unfriendly here. Once of the things I realized quickly when I started tinkering with Docker is the myriad of ways to do things and the (strong) opinions pulling on the multiple directions.

We cannot possibly support all usecases here, and this is not a common one AFAICT. Now, the fix is probably a one-liner, so feel free to send a PR!

**Comment by sapkra** [comment]
Sorry if it sounded a bit harsh - but very direct communication is somehow part of my cultural background. Sorry for this misunderstanding - it was definitely not meant unfriendly.

I have a strong opinion on that topic. For me it's absolutely clear that docker containers are stateless so you will never run stuff in them which should be persistent. To update an image you have to pull or rebuild it. But yeah, maybe it would make sense to upgrade the other installed packages while building.

@saghul WDYT? Should we run `apt upgrade` in the Dockerfiles?

**Comment by saghul** [comment]
We actually already do, at build time. If supporting this use case is not too much trouble let’s have it I think.

**Comment by mdosch** [comment]
I am also very new to docker, actually I only use it for jitsi meet as the debian package is no real teamplayer (it broke my nginx, it forced me to completely rework my prosody config at first update and silently overwrote my coturn config) so I'd be interested what is the best way to update. The manual stops after first installation and doesn't mention updates. So far I just did 'git pull' and 'docker-compose restart' but I am not sure if this is the prober approach.
