### ISSUE TITLE
Documentation of configuration options

### ISSUE THREAD

**Issue by klsdfgi4l223** [jitsi/docker-jitsi-meet#490]
Hi all,

how do I configure additional settings like DISABLE_JOIN_LEAVE_NOTIFICATIONS or disableAudioLevels? Can these be set in .env? If not - is there another way to set these in a way that will survive updates of docker-containers or the recreation of the config-directory? 
I can't find anything in the documentation on these settings like this, but I might have missed it ;-)

**Comment by IAmRC1** [comment]
I am also looking to change config files to fix video resolution and height constraints to Low Def but the changes are not taking effect. Can you help?

**Comment by vishalpathak24** [comment]
Same Problem its not working by overriding in `interface_config.js`

**Comment by pat-s** [comment]
One needs custom `config.js` and `interface_config.js` in `config/` within the "web" container. Not all configs can be set via env vars yet, see [here](https://github.com/jitsi/docker-jitsi-meet/issues/768).

**Comment by OE1FEU-DF5JT** [comment]
I am still confused and hope that someone can bring clarity into my clouded thinking. I have built jitsi-meet as per this documentation: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/ on Rocky Linux 9.

This runs on a well connected dedicated server in a data center, which otherwise is pretty much idle mostly. My hopes is to use a video conferencing system that offers both high quality video and audio. Audio has a high priority, because I want to present concert grand pianos to remote customers and also hold interactive piano lessons.

The documentation states that "4. Create required CONFIG directories" and here I read about custom-config.js and interface_config.js - in a directory that doesn't exist in my installation. I can see that this thread is now three years old, but I haven't found any helpful enlightenment that steers me to where I want to go. 

Is it correct that I should create a /web/rootfs/config/ directory and put those two modified .js config files or/and can/must I put the necessary paramaters into the .env file? And where goes which parameter, specifically those dealing audio/video bitrate, stereo on, AGC, noise suppression off etc to get best results for music conferencing, including FHD camera resolution?

Thanks.

**Comment by saghul** [comment]
> The documentation states that "4. Create required CONFIG directories" and here I read about custom-config.js and interface_config.js - in a directory that doesn't exist in my installation. I can see that this thread is now three years old, but I haven't found any helpful enlightenment that steers me to where I want to go.

I just updated that part, those files are located in `CONFIG/web` so that is `~/.jitsi-meet-cfg/web` by default.

**Comment by saghul** [comment]
I'm going to close this since I think the original purpose was fulfilled.
