### ISSUE TITLE
[web] Configure Matomo settings using environment variables

### ISSUE THREAD

**Issue by ludovicm67** [jitsi/docker-jitsi-meet#529]
Once https://github.com/jitsi/jitsi-meet/issues/6411 is done, it can be very useful to be able to configure Matomo settings using environment variables, like for example:

- `MATOMO_ENDPOINT`: full URL of Matomo instance,
- `MATOMO_SITE_ID`: the site ID given by the Matomo instance

**Comment by c-prompt** [comment]
Thanks for the great functionality. As you improve it, please consider grabbing variables sent via the [JWT token authentication](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md) to include as [Matomo custom variables](https://developer.matomo.org/guides/tracking-javascript-guide#custom-variables) (e.g., `_paq.push(['setCustomVariable','1','VisitorType','Member']);`) or other user-related data such as [UserID](https://developer.matomo.org/guides/tracking-javascript-guide#user-id) (e.g., `_paq.push(['setUserId', 'USER_ID_HERE']);`).

Since it's currently limited to what's defined in config.js, it'd be useful for this to be a bit more customizable. Additionally, there are use cases when you want to send multiple Matomo Site IDs (e.g., record visit on main site and also record same visit on different site) so it'd be great to designate a Matomo custom variable (e.g., setSiteId) in the JWT and, if the MatomoHandler class sees the JWT custom variable, it can add a _paq.push (e.g., `_paq.push(['setSiteId', {$JWT_CUSTOM_IDSITE}]);`)
