### ISSUE TITLE
Better error message in android app if there are cert errors

### ISSUE THREAD

**Issue by Cyber1000** [jitsi/docker-jitsi-meet#574]
I'm not quite sure if this is the right repo for the android app, but couldn't find any better (jitsi-android is archived for example)

If I have a cert (not the fullcert) used on an own jitsi-server following happens:
- I can log in via web
- I can't login via app, it suddenly just states "The connection has been disconnected"

My problem is mainly the message, if it has said, "server not trustworthy" or "wrong certificate" or even better "fullcert missing" (or something that like) I wouldn't have wasted time.

**Comment by saghul** [comment]
jitsi-meet is the right repo as it contains the source for the web and mobile apps.

As for the issue itself, alas we don’t know what caused the failure at the JS level, since this is abstracted by the React Native framework.

If you have any suggestions, they’d be most welcome!

**Comment by JacBra** [comment]
Hi, I have experienced the same. The thing is that when e.g. the needed root/intermediate certificates are not included in $CONFIG/keys/cert.key then the Android App only (immediately) states "The connection has been disconnected", while via a browser it works perfectly since the browser 'knows' these root certificates already. So if the Android App could give any message that there is a certificate error, then troubleshooting is a lot easier. Not sure if this is possible, but I wanted to share this experience anyway.

**Comment by Cyber1000** [comment]
Yes I've asked here: https://community.jitsi.org/t/connecting-from-android-app-to-own-server-with-letsencrypt-cert-and-custom-port-fails/46130
And found the answer some days later on my own. 

But neither the android-message nor the log entries serverside nor communication-sniffing via wireshark was helpful. Communication seemed to die at the first moment of contact.

But thanks for the hint of the abstraction by React, maybe I'll have a look when having time.
