### ISSUE TITLE
Replace deprecated UseConcMarkSweepGC by G1 or Shenandoah 

### ISSUE THREAD

**Issue by sych74** [jitsi/docker-jitsi-meet#626]
At the moment **jvb** and **jicofo** are using UseConcMarkSweepGC which is deprecated. I believe it's necessary to change the deprecated GC by one of the more advanced GCs like G1 or Shenandoah. These collectors unlock a better elasticity of JVM by automatic release of unused RAM back to OS. There is an overview presentation of [Java elasticity](https://www.slideshare.net/jelastic/elastic-jvm-for-scalable-java-ee-applications-running-in-containers-jakartatechtalks). As a result, the applications will consume less resources at idle stage. At the moment the resource usage is constantly growing up even if there are no active meetings.

<img width="656" alt="Screenshot 2020-06-03 at 11 01 44" src="https://user-images.githubusercontent.com/17590698/83611638-ecca3980-a589-11ea-8297-a5d50e0e1b9f.png">

**Comment by bgrozev** [comment]
Perhaps this is something specific to the docker setup that I'm missing, but jicofo should be using the JVM's default (which is Parallel GC on java 8 and G1 on newer java versions). We haven't worked on optimizing this, as it hasn't been a bottleneck for us (running not much else thatt jicofo on a separate vm). Using G1 or Shenandoah to improve elasticity sounds reasonable. Anoher thing that could help is to simply reduce the heap size -- it runs with 3GB by default which is definitely overkill.

For jitsi-videobridge the situation is different. As we're routing multimedia we want to minimize delay, and higher memory usage and CPU overhead is a tradeoff we pay to reduce stop-the-world pauses due to GC. To achieve this we use UseConcMarkSweepGC and a memory pool in java. We use CMS because in our experiments it performed better than G1. We'd like to test with Shenandoah and different G1 configurations, but I don't know when we will have the resources to do it. Until we do, I would rather stick to CSM. Note that because we use a memory pool in java, switching the GC won't improve the elasticity much -- as far as java is concerned all that memory is in use. Again, elasticity is not a concern for us in the way we run these machines, but you can certainly experiment. If you do, be aware that you might end up with long pauses during GC leading to visual freezes in the client.

**Comment by sych74** [comment]
>  jicofo should be using the JVM's default 

Sorry, my fault, somehow I got confused. It does not define specific GC at the start options, so yes it uses default Parallel GC which is not compacting / elastic at all. Migration to java 12+ will unlock the new options of G1.

> Anoher thing that could help is to simply reduce the heap size -- it runs with 3GB by default which is definitely overkill.

What is a better default for jicofo from your point of view? 

> I would rather stick to CSM

How long do you believe jitsi-videobridge will keep using java 8?

> Note that because we use a memory pool in java
 
Do you mean Native Memory? 

> Again, elasticity is not a concern for us in the way we run these machines, but you can certainly experiment. If you do, be aware that you might end up with long pauses during GC leading to visual freezes in the client.

Thank you for the warning. Definitely visual freezes are not expected at all. 
I do believe it's possible to tune JVM for different kind of workloads: high load with many ongoing meetings 24/7, moderate load or mostly idle environments. With java 12+ it's more flexible now, you can give priority for performance and low GC pauses when JVM is under a heavy load and at the same time get memory compaction if the app is in idle state. Does it make sense to introduce a dedicated env variable that defines load profile: HIGH, MID, LOW?

**Comment by bgrozev** [comment]
> What is a better default for jicofo from your point of view?

I don't have a conclusive answer. I see a machine that's been up for a while and peaked at ~1100 concurrent conferences, which has an old generation capacity of just over 400MB. I think that's an indication that it never needed more than that. So, I think 1GB is a reasonable number.

> How long do you believe jitsi-videobridge will keep using java 8?

I think it can already run on java 11.

> Do you mean Native Memory?

No, java memory,  see [here](https://github.com/jitsi/jitsi-videobridge/blob/master/src/main/java/org/jitsi/videobridge/util/ByteBufferPool.java).

> Does it make sense to introduce a dedicated env variable that defines load profile: HIGH, MID, LOW?

I think it's too early for this. We need experimentation to see how it behaves with newer JVMs and in different conditions.

**Comment by sych74** [comment]
> So, I think 1GB is a reasonable number.

Ok. I just noticed you added JICOFO_MAX_MEMORY env variable 7 days ago. Thank you, it helps to perform memory tuning experiments easily.   

> I think it can already run on java 11.

I see the [latest jicofo docker image](https://hub.docker.com/layers/jitsi/jicofo/latest/images/sha256-cdbe3491e65822c281f47c8067279811d81b3f6ac8e2e2e2714ec841f3dcfd19?context=explore) is using openjdk-8-jre-headless. What is the simplest way to use / test a docker image with java 11?

> No, java memory, see [here](https://github.com/jitsi/jitsi-videobridge/blob/master/src/main/java/org/jitsi/videobridge/util/ByteBufferPool.java).

So it's a custom byte buffer pool implementation which stores data in the **heap** memory. And you believe it's not elastic as the pool does not clean itself. Is it a correct statement? Just want to get a better understanding of the concern.   
 
> I think it's too early for this. We need experimentation to see how it behaves with newer JVMs and in different conditions.

Can I help you somehow here? Do you need compute resources for running experiments?

**Comment by bgrozev** [comment]
> I see the [latest jicofo docker image](https://hub.docker.com/layers/jitsi/jicofo/latest/images/sha256-cdbe3491e65822c281f47c8067279811d81b3f6ac8e2e2e2714ec841f3dcfd19?context=explore) is using openjdk-8-jre-headless. What is the simplest way to use / test a docker image with java 11?

No idea. Maybe @saghul has a suggestion?

> So it's a custom byte buffer pool implementation which stores data in the **heap** memory. And you believe it's not elastic as the pool does not clean itself. Is it a correct statement?

Yes.

> Can I help you somehow here? Do you need compute resources for running experiments?

We do not need computing resources, but there are several ways you can help.

Using java 11+ would be the first step in any of this, so testing and verifying that the bridge works and performs well would be useful.

As I said before we would like to do more GC tests, but they take a lot of time and it is currently not on our plan. It is unlikely we'll get to it in the next few months. I can give you the details about the previous test, so you could either give feedback, or adapt it and run it yourself. 

You could open PRs to make things more easily configurable: GC params, enable/disable the memory pool, or other things you find you need to tweak for your environment.

**Comment by sapkra** [comment]
@sych74 Saghul already commented regarding upgrading to Java 11. https://github.com/jitsi/docker-jitsi-meet/pull/227#issuecomment-624486062

Here you can find the related PRs: https://github.com/jitsi/docker-jitsi-meet/pull/227 https://github.com/jitsi/docker-jitsi-meet/pull/440

But feel free to test it. The result would definitely be interesting.

**Comment by saghul** [comment]
FWIW, I’ve started to prepare the update to Buster, but maintaining the use of Java 8, since that’s what we run in production ourselves.

This is possible with the AdoptOpenJDK packages, and some adjustments I made to the debian/control files so we don’t depend on specific JRE implementations. This also makes it possible to experiment with OpenJ9 instead of HotSpot for instance.

**Comment by sych74** [comment]
> It is unlikely we'll get to it in the next few months. I can give you the details about the previous test, so you could either give feedback, or adapt it and run it yourself.

Thank you, testing details will be helpful. We have a JMeter cluster for web and e-commerce - 10,000 concurrent users. I believe for jitsi we need a different load testing logic. 

> This is possible with the AdoptOpenJDK packages, and some adjustments I made to the debian/control files so we don’t depend on specific JRE implementations. 

This will unlock more experiments 👍

> This also makes it possible to experiment with OpenJ9 instead of HotSpot for instance.

J9 can reduce memory usage significantly, but such migration should be tested even more carefully.

**Comment by bgrozev** [comment]
> Thank you, testing details will be helpful. We have a JMeter cluster for web and e-commerce - 10,000 concurrent users. I believe for jitsi we need a different load testing logic.

Can you send me an email please? Boris at jitsi org

**Comment by agrrr3** [comment]
Just because i did not find it documented anywhere: it is possible (now) to set the garbage collector in the jvb config, at least on ubuntu (i.e. in `/etc/jitsi/videobridge/config`) by adding the entry `VIDEOBRIDGE_GC_TYPE=ShenandoahGC`.
This will add the necessary -XX:UseShenandoahGC to the java command.

And it seems to work fine (using java-14-openjdk). Note i did not measure and I only did some smoke testing yet. But I would not expect it to run worse.

Also note Shenandoah was backported to java11-openjdk, so it should be available for most people.

Maybe you could document that startup parameter(s) on the homepage?

**Comment by bgrozev** [comment]
I think we can close this one now. There's been many changes and we didn't mention any of them here. To summarize:

* Both jicofo and JVB now target java11
    * We use 11 for production machines and PR testing
    * We also run unit tests on 17 and expect it to be supported, but the testing is limited
* JVB defaults to using G1 GC on all JVMs
    * We did validation tests on it and it performed well
    * I opened jitsi/jitsi-videobridge#1980 to document the VIDEOBRIDGE_GC_TYPE option
* Jicofo still uses the default JVM GC
    * I think that's G1 on most supported versions
    * We still don't think it's important and don't have overrides
    
    
Thanks everyone for the feedback and suggestions!
