### ISSUE TITLE
Jibri Recording requires Display Name

### ISSUE THREAD

**Issue by JacBra** [jitsi/docker-jitsi-meet#634]
I enabled requireDisplayName to require all users to enter a Display Name when they enter a meeting.
However, this is also applied for the Jibri recording session. As a result this popup is always on top in the recording. Does anyone know how to prevent this?

**Comment by gfoglietta** [comment]
Same problem

**Comment by sapkra** [comment]
I think this isn't a problem with the docker environment instead it should be fixed in jitsi-meet and/or jibri repository. Seems like a weir edge case

@saghul WDYT? Does it make sense to move the ticket to a different repo?

Here is also a hint what is causing the bug:
https://community.jitsi.org/t/requiredisplayname-true-window/18240/9

**Comment by saghul** [comment]
@sapkra Indeed. I created https://github.com/jitsi/jibri/pull/300 since it's a one line change.
