### ISSUE TITLE
Making Octo config pre-defined in Jicofo/Jvb sip files 

### ISSUE THREAD

**Issue by prayagsingh** [jitsi/docker-jitsi-meet#643]
Hello @saghul @sapkra This is more of a question about adding pre-define `Octo` config for `Jicofo` and `jvb` in `sip-communicator.properties` file like below. Currently If someone want to use `Octo` then it requires adding `Octo` config manually in `sip-communicator.properties` file and then build their own `docker image`. By adding this  we can ensure that by just setting `ENABLE_OCTO=1` and some additional octo `env` variables, they can start using `Octo` and They don't need to build the `docker image.` 

**jvb sip file**
```
# Octo config
{{ $ENABLE_OCTO := .Env.ENABLE_OCTO | default "0" | toBool }}
{{ if $ENABLE_OCTO }}
org.jitsi.videobridge.octo.BIND_ADDRESS={{ .Env.HOST_IP }}
org.jitsi.videobridge.octo.PUBLIC_ADDRESS={{ .Env.HOST_PUBLIC_IP }}
org.jitsi.videobridge.octo.BIND_PORT={{ .Env.OCTO_BIND_PORT }}
org.jitsi.videobridge.REGION={{ .Env.OCTO_REGION }}
{{ end }}

```

**jicofo sip file**

```
# setting octo config
# for testing --> SplitBridgeSelectionStrategy
# for production --> RegionBasedBridgeSelectionStrategy
{{ $ENABLE_OCTO := .Env.ENABLE_OCTO | default "0" | toBool }}
{{ if $ENABLE_OCTO }}
org.jitsi.jicofo.BridgeSelector.BRIDGE_SELECTION_STRATEGY={{ .Env.BRIDGE_SELECTION_STRATEGY }}
{{ end }}

```

Please suggest.

**Comment by prayagsingh** [comment]
@saghul Any thoughts on this?

**Comment by kahidna** [comment]
any update on this?

**Comment by saghul** [comment]
We should have closed this, octo support has been ready on the images for a while 😅__

**Comment by kahidna** [comment]
I see,, thank you for the fast response @saghul .

can you give some brief on how to verify the octo is working?
I tried to find how to verify it by myself, but I just found the old way to verify it,
for example using Netcat just like described in this thread.

https://community.jitsi.org/t/need-to-test-that-whether-its-working-or-not-after-enabling-octo-octo-configuration/53063/9?u=rasos

and then I figured out that the new version of Jitsi has a different way of implementing octo

from here: https://git.fairkom.net/hosting/fairmeeting/-/issues/85#note_57752 

is there documentation for implementing the new version of Jitsi with Octo that I can try?
I already deployed 2 JVB using docker-compose in this repository with some modifications for the swarm cluster.

Both JVB runs well, but I want to achieve a single conference with distributed participant among the JVB's node which does seem not to work because I see only one JVB with a high load while the other one is just idle (I check it using htop)

I read the documentation to use `SplitBridgeSelectionStrategy`, but still not working.
is it okay if we use this GitHub issue or should I move it to Jitsi's community forums?
