### ISSUE TITLE
NAT_HARVESTER_LOCAL_ADDRESS make no effect

### ISSUE THREAD

**Issue by pca-homsi** [jitsi/docker-jitsi-meet#647]
ICE candidates doesn't includes the IP provided with NAT_HARVESTER_LOCAL_ADDRESS but the internal docker container ip

In which case NAT_HARVESTER_LOCAL_ADDRESS is needed ?

**Comment by bgrozev** [comment]
You need the pair of `NAT_HARVESTER_LOCAL_ADDRESS` and `NAT_HARVESTER_PUBLIC_ADDRESS`

**Comment by pca-homsi** [comment]
what i need actually is having this kind of communication :
Client1 ---`PUBLIC_IP`-- NAT --- JVB --`NET1`-- ROUTER ---`NET2` --- Client2

I set
`NAT_HARVESTER_PUBLIC_ADDRESS` = PUBLIC_IP
`NAT_HARVESTER_LOCAL_ADDRESS `= LOCAL IP OF JVB IN NET1

When i try to make a communication it keep deconnecting and retrying.
But if both clients are from Public area the call is ok

**Comment by bgrozev** [comment]
You need to set the local address to the interface that the bridge uses to connect to client 1.

**Comment by uvwild** [comment]
@bgrozev      I am trying to get this work in a  k8s cluster using helm.

So I have 
PUBLIC_IP forwarding to 
 -->       DOCKER_HOST== nodeIP
      -->        containerIP == podIP

I am not sure how the mapping works since docker_host_IP is not public but used as the public address in most examples.
I tried various combinations but never got a stable connection.

How does this map to harvester local and public addresses?

i would intuitively use Public IP as public address and podIP as local address.
but this measn the docker host in between is missing.....

**Comment by damencho** [comment]
> i would intuitively use Public IP as public address and podIP as local address.
> but this measn the docker host in between is missing.....
This is correct. The bridge needs to know its public IP as this IP is added to the signaling which then is sent to clients. So the clients need to receive the correct public IP on which they will start sending packets. Those packets just need to reach jvb and jvb will be sending packets back. There is no other logic and the docker host IP is not needed as long as the packets reach jvb.

**Comment by bgrozev** [comment]
What Damencho said. The local address for the mapping harvester should be the address the bridge binds on (I don't know how that maps to an address with docker/k8s).
