### ISSUE TITLE
[noob] web service not working

### ISSUE THREAD

**Issue by aldaleel** [jitsi/docker-jitsi-meet#74]
Thanks for the great project,
I have followed the tutorial here and I have found no errors 
I have tried to access DOCKER_HOST_URL:8000 didn't work
as if there was no webserver running......
I have used bash on the web container and found nginx not running
I have started nginx , I get the default nginx page!
I tried about everything relevant on the .env file
Please Help
// .env file: attached
I want to use it on the local network without https and then port forward to the internet
but I can change initial plan if needed

[dotenv.txt](https://github.com/jitsi/docker-jitsi-meet/files/2961346/dotenv.txt)

Using: Oracle GNU/Linux

**Comment by YUEJINYUAN** [comment]
This group of containers will start in sequence. If you have some problems in starting, it is recommended to close them first (you can delete those already built, after all, it is just beginning). After rebuilding, if you still haven't opened 8000, you can go to jitsi_web and look for the nginx configuration file to see if there is any problem, emmm...

Other case 1, remember to name it. env, although I don't know if you have done this, at the same time, I suggest you refer to env. example first, and try to build your first time without changing it, which may be helpful.

Other cases 2, if your system is Windows Home Edition, there may be problems with container port mapping. Linux or other versions of Windows are recommended.

Other cases 3, more detailed information, you need to provide, including the docker-compose up-d at that time，maybe I can determine what the problem is.

**Comment by saghul** [comment]
@aldaleel nginx may take some time (up to a minute) to start the first time because it's generating the DH parameters. Please let it finish (check the logs, it mentions this) and try again after it's ready.
