### ISSUE TITLE
config.js reset to default when dockerjitsimeet_web_1 is restarted

### ISSUE THREAD

**Issue by mdwatz** [jitsi/docker-jitsi-meet#764]
Hi,

since `stable-5076` my `~/.jitsi-meet-cfg/web/config.js` is reset to default values when you restart the web-container.
Also the user defined config.something values at the end of the file are reset to default and ignored.

Steps to reproduce:

1. Edit `config.js` and change some value
2. Restart Docker container `docker restart dockerjitsimeet_web_1`
3. Value in `config.js` is reset to default and ignored 

Where can I set my own settings now?

**Comment by NullIsNot0** [comment]
It's because of this PR: https://github.com/jitsi/docker-jitsi-meet/pull/619

**Comment by larscom** [comment]
I noticted this as well, i just configured the config.js file and restarted the container.. and poof everything back to default..

**Comment by ludovicm67** [comment]
Since #619 you can use environment variables to configure Jitsi Meet.

You can find in the [`docker-compose.yml`](https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml) file all environment variables used per service under the `environment` key.

If you want to see defaults values, you can have a look at those two files:
- [settings-config.js](https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/settings-config.js)
- [system-config.js](https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/system-config.js)

You can also change the `config.js` file located at `/defaults/config.js` inside the Docker container (modified file should be present in the container before it starts).

**Comment by mdwatz** [comment]
Ah. I got confused. That's not the behaviour I expected.

From my perspective, I'm used to store all my settings outside of the container in the config directory `~/.jitsi-meet-cfg`. 
When starting the container this directory will get mounted as `/config` inside of the container, which makes sense.

Now your config will be overwritten by default values, if you didn't set some environment first, which is in some `/default` folder.
I prefer setting up everything in the config in the config-directory and not in some git repository folder. 
It is OK to overwrite settings via environment, e.g. when testing something. But environment should come second and config first. Now you have some default environment which overwrites the config in the config-directory. Usually it's the other way round: config would overwrite default values. That really got me confused.

But thanks for the clarification. I love using jitsi and I appreciate all the work done by the community and especially the developers. Thank you!
