### ISSUE TITLE
How to secure the creation of a meeting room

### ISSUE THREAD

**Issue by jmereaux** [jitsi/docker-jitsi-meet#8]
Hi,

I am looking for a way to secure the creation of the meeting rooms.
Can the configuration described [here](https://github.com/jitsi/jicofo#secure-domain) can be applied to the Jitsi Docker setup?

Thanks

**Comment by saghul** [comment]
Yes. You can run the containers once so all files are generated in the `CONFIG` directory. Then stop them, modify the files to your liking and restart. You'll need to `docker exec` into the prosody container for creating users.

**Comment by ovizii** [comment]
I was looking for the same info, thanks for the link provided. 

To be honest, it looks a bit over my head. I'm not quite new to Docker, I know how to access and edit the config files BUT there are too many moving points here... 

What happens if I edit the config files and later use docker-compose up -d again to update to a newer image, will the .env file overwrite my config files? (I assume yes) 

Does anyone have more pointers how to set up authentication, those instructions look extremely complicated :-(

**Comment by saghul** [comment]
> What happens if I edit the config files and later use docker-compose up -d again to update to a newer image, will the .env file overwrite my config files? (I assume yes)

No, your files won't be overwritten.
