### ISSUE TITLE
What does @root_path exactly mean?

### ISSUE THREAD

**Issue by chanochan** [jitsi/docker-jitsi-meet#928]
Hi.

During development, I encountered a line of Nginx config, although I searched about it a lot I couldn't find out what that exactly means. As the title explains my problem well, it's about [this line](https://github.com/jitsi/docker-jitsi-meet/blame/master/web/rootfs/defaults/meet.conf#L74).

Any idea? Specially you @timonegk

**Comment by timonegk** [comment]
Hi,
the changes I made to the configuration file come from [the upstream jitsi repository](https://github.com/jitsi/jitsi-meet/) and the nginx configuration can be found [here](https://github.com/jitsi/jitsi-meet/blob/19bf027b8b041002490dcb83d87cda7fba1f4f54/doc/debian/jitsi-meet/jitsi-meet.example).

But I can still explain the meaning. From the [nginx docs](https://nginx.org/en/docs/http/ngx_http_core_module.html#location)
> An nginx location beginning with `@` defines a named location. Such a location is not used for a regular request processing, but instead used for request redirection.

In our case, the `@root_path` location is used in the [location above it](https://github.com/jitsi/docker-jitsi-meet/blob/24781e38bf5eb908a7057982eb19b7296cfbf53b/web/rootfs/defaults/meet.conf#L70). Due to the evaluation order of nginx locations (non-regexes first, then regexes in order of appearance in the config file), this location directive is the last to be evaluated. It defines a sort of catch-all for everything that would be a valid roommate, that is all URLs that do not contain any of the symbols `/?&:'"`. (By the way, you can test that on https://meet.jit.si/ by entering a URL with any one on those characters, you will see the 404 error page). In the location directive, the [try_files](https://nginx.org/en/docs/http/ngx_http_core_module.html#try_files) directive is used to check if a file with that name exists. If no such file exists, the request is redirected to the location `@root_path`. This location is defined below, redirecting all traffic (the regex matches everything) internally to `/` but leaving the URL in the clients browser as it is. This serves the `index.html` file located in `/usr/share/jitsi-meet/`, as defined by the `index` and `root` directives at the top of the file. The javascript in `index.html` parses the URL to provide the specified room.

I hope this helps!
