### ISSUE TITLE
Websocket 403

### ISSUE THREAD

**Issue by tiramon** [jitsi/docker-jitsi-meet#952]
This looks similar to #942 but i'm not sure it it is the same, he somehow got a localhost in the wss url while mine shows the correct url

I tried with my mobile android and it worked perfectly
But in Browser (Edge, Chrome) i always get
![image](https://user-images.githubusercontent.com/642242/107701302-03986280-6cb9-11eb-9eb5-b93752c06504.png)

I set HTTP_PORT to 80 and HTTPS_PORT to 443 and also tried PUBLIC_URL=https://jitsi.tiramon.de with and without port 443
in both cases the websocket tried to connect to the same url

![image](https://user-images.githubusercontent.com/642242/107700816-51609b00-6cb8-11eb-863a-4111d521c58d.png)

Tried HEAD and currently running stable-5390-3

**Comment by tiramon** [comment]
When i call the wss url in another window chrome shows me a ERR_DISALLOWED_URL_SCHEME
When i call the url as http https://jitsi.tiramon.de/xmpp-websocket it tells me
`It works! Now point your WebSocket client to this URL to connect to Prosody.`
sounds there really is some routing problem ...

**Comment by paulo20223** [comment]
My config nginx

upstream web_rtc_server {
    server webrtc-server:80;
}

server {
    server_name example.com;
    ssl_certificate /src/cert/cert.crt;
    ssl_certificate_key /src/cert/cert.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    ssi on;
    ssi_types application/x-javascript application/javascript;
    client_max_body_size 0;

    location / {
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
            proxy_pass http://web_rtc_server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;

        }


    location /xmpp-websocket {
    proxy_pass http://web_rtc_socket/xmpp-websocket?$args;
    proxy_http_version 1.1;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Host $host;
    proxy_read_timeout 900s;

}

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
}

Its work

**Comment by tiramon** [comment]
Is this the config for a proxy infront of the docker construct?
If yes ... i don't use a proxy ...

And if that is not a proxy config ... why does it look so different from the one created by docker ...

**Comment by tiramon** [comment]
I also tried ENABLE_XMPP_WEBSOCKET=0 as mentioned in other issues, that way i can connect to the room, but in the background there are still websocket errors thrown
and i couldn't get video working
Tried with my laptop and my phone and both saw their own video but not the one of the other account in the room

**Comment by tiramon** [comment]
ok ... this time with  ENABLE_XMPP_WEBSOCKET=0 everything seems to work as expected ... i have no idea what is happening there in the background ... i didn't change anything except switching it on once and off again ...

**Comment by tiramon** [comment]
and then the video doesn't work again ... damn this is pretty unstable :(

**Comment by tiramon** [comment]
when my guest leaves the room and i'm the only one while i share my screen my session crashs ... wow ...

**Comment by saghul** [comment]
What did you set PUBLIC_URL to? Please provide JS console logs, otherwise it's very hard to help diagnose the problem.

**Comment by T-101** [comment]
I've been struggling with this "disconnected"-loop issue all night too. I solved it by changing all ":latest" in docker-compose.yml to ":stable-4627-1" and now I can jitsi again with my friends

**Comment by debendraoli** [comment]
I also stumbled on this, bugged me for couple of days, turns out cert issue.

https://community.jitsi.org/t/solved-permission-denied-for-jibri-when-using-web-socket/89725

**Comment by saghul** [comment]
No follow up on the logs. Closing.

**Comment by marner2** [comment]
@saghul I'm having the same issue here, I'll post my console logs:

https://gist.github.com/marner2/1ba5983d2aaf50e8fe0bea0e0865b535#file-jitsi-jmarner-com-1616178004711-log

**Comment by prayagsingh** [comment]
Hello @sapkra @saghul  I have a question about using websocket on k8s. my cluster is running in VPC and the worker nodes can't access the internet directly. To access the internet I have to enable a Gateway(floating-IP).  I'm trying to use Octo hence can't use **service** as **`type: LoadBalancer`** because it only allows TCP not UDP protocol hence using **service** **`type: NodePort`**. 

**Details about IP's and domain**
1. Main IP is to get the ssl-certificate via ha-proxy ingress and service is `type: LoadBalancer`. It mapped a domain-name(some gibberish domain like 1234.mydomain.ibm.cloud ) as External-IP. the I mapped it to my main domain name `meet.example.com` as a `CNAME` in route53. 
2. Gateway(public-ip for worker nodes to access the internet). lets say `128.1.1.1`
3. then there is a instance IP which acts as both internal and external-ip 
```
NAME          STATUS   ROLES    AGE    VERSION       INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
10.244.1.1   Ready    <none>   3d1h   v1.20.4+IKS   10.244.1.1   10.244.1.1   Ubuntu 18.04.5 LTS   4.15.0-136-generic   containerd://1.4.4
```
4. Container/pod-Ip: `172.17.12.115`

Now what should be the value of 
1. `octo.public-address` in jvb.conf
2. org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=   ??
3. org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS= ?? 
4. Also Can I use port 30600 instead of 9090  as a `http-servers.public.port` value?

**NOTE:** running 5 worker nodes. 

Please help. I'm trying to figure out how to make websockets work with k8s from last couple of weeks. My current setup is on docker-swarm and because of limitation of autoscaler I'm moving to K8s.
