### ISSUE TITLE
Documentation: Add Reverse Proxy Guidelines

### ISSUE THREAD

**Issue by iUnknwn** [jitsi/docker-jitsi-meet#962]
Would it be possible to add reverse proxying guidelines to the current documentation?

Right now, the documentation is excellent, but it doesn't cover running the docker image behind a proxy, which I suspect is pretty common. It would be great if, at a minimum, there was an example config explaining, for example, what items need to be proxied (the HTTP root, as well as any web socket connection URLs), what forwarding headers to use so the logs are correct, etc.

**Comment by matheusfillipe** [comment]
That would be helpful! By searching through the forum and issues I found these to work:
Inside your apache2 vhost
``` 
...
SSLProxyEngine on                                        
                                                               
ProxyPreserveHost On                                      
RequestHeader set X-Forwarded-Proto "https"              
ProxyPass "/" "http://localhost:8000/"                         
ProxyPassReverse "/" "http://localhost:8000/"                         
                                                                      
ProxyPass "/http-bind" "http://localhost:8000/http-bind/"      
ProxyPassReverse "/http-bind" "http://localhost:8000/http-bind"       
                                                                      
RewriteEngine on
RewriteCond %{HTTP:Connection} Upgrade [NC]            
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule ^/?(.*) "ws://127.0.0.1:8000/$1" [P,L] 
ErrorLog     /var/log/apache2/meet-error_log                
CustomLog          /var/log/apache2/meet-access_log common

...

``` 

And on nginx:
``` 
 ssl_session_cache  builtin:1000  shared:SSL:10m; 
 ssl_protocols  TLSv1 TLSv1.1 TLSv1.2; 
 ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4; 
 ssl_stapling on; 
 ssl_stapling_verify on; 

 access_log  /var/log/nginx/meet_access.log; 
 error_log   /var/log/nginx/meet_error.log; 

 location / { 
     proxy_pass http://127.0.0.1:8000; 
     proxy_set_header X-Forwarded-For $remote_addr; 
     proxy_set_header Host $http_host; 
 } 

 location /xmpp-websocket { 
     proxy_pass http://127.0.0.1:180/xmpp-websocket; 
     proxy_http_version 1.1; 
     proxy_set_header Upgrade $http_upgrade; 
     proxy_set_header Connection "upgrade"; 
     proxy_set_header Host $host; 
     tcp_nodelay on;
}

```

In order for jibri to work you need to leave `DISABLE_HTTPS=0  ` on your .env.

**Comment by AquaL1te** [comment]
Best is to not use localhost:port for the proxy_pass. At least that's my experience. When I reboot and the Jitsi containers come up automatically, I have to restart Nginx to make it work. Probably because the socket wasn't created yet.

Discourse uses UNIX file socket to proxy towards, which works very stable! It's also a performance benefit, because you don't have to use the TCP/IP stack, this is also more secure.

Check their setup [here](https://meta.discourse.org/t/adding-an-offline-page-when-rebuilding/45238). It would be cool if there was an **environment variable to enable UNIX file sockets** for the external reachable things so that Nginx can simply do something like this, but then with Jitsi:

```
  location / {
    proxy_pass http://unix:/var/discourse/shared/standalone/nginx.http.sock:;
    proxy_set_header Host $http_host;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
```

**Comment by saghul** [comment]
I started here: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#running-behind-a-reverse-proxy will try to add complete Nginx and Apache examples as time allows.

**Comment by SourceCodeDeleted** [comment]
I want to add this here, because I thought the instructions left something to be desired. I spend a good amount of time trying to work on the WS socket.  With the error "You have been disconnected".
As I understand the mod_proxy_wstunnel might be deprecated and or ignored already in HTTPD, but it works like this for now. 

I have mine behind a HTTPD rev proxy. my app points to my.app/meet/ to get to the jitsi page.

In the .env file.

```
DISABLE_HTTPS=1
ENABLE_HTTP_REDIRECT=0
ENABLE_LETS_ENCRYPT=0
PUBLIC_URL=https:/my.app
```

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName my.app

    ProxyPreserveHost On
    RewriteEngine On

    <IfModule mod_proxy_wstunnel.c>
        # WebSocket proxy rules
        ProxyPass /meet/xmpp-websocket ws://localhost:8000/xmpp-websocket
        ProxyPassReverse /meet/xmpp-websocket ws://localhost:8000/xmpp-websocket

        ProxyPass /meet/colibri-ws/ ws://localhost:8000/colibri-ws/
        ProxyPassReverse /meet/colibri-ws/ ws://localhost:8000/colibri-ws/
    </IfModule>

    # General proxy rules for /meet
    ProxyPass /meet/ http://localhost:8000/meet/
    ProxyPassReverse /meet/ http://localhost:8000/meet/

    # Static asset paths
    ProxyPass /sounds/ http://localhost:8000/sounds/
    ProxyPassReverse /sounds/ http://localhost:8000/sounds/

    ProxyPass /libs/ http://localhost:8000/libs/
    ProxyPassReverse /libs/ http://localhost:8000/libs/

    ProxyPass /images/ http://localhost:8000/images/
    ProxyPassReverse /images/ http://localhost:8000/images/

    # Catch-all for frontend
    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/

    # SSL configuration
</VirtualHost>
</IfModule>
```

**Comment by mitexleo** [comment]
Please suggest configuration for IIS.
