### ISSUE TITLE
Problems with JitsiMeet V0.9 for Synology

### ISSUE THREAD

**Issue by dkonanjp** [jitsi/docker-jitsi-meet#964]
**Dear @TosoBoso**,
I installed the last version of JitsiMeet V 0.9 on my **Synology DS218+ with RAM = 10 GO**
Only the default option and in my browser (Firefox, with **https:192.168.x.xx:8443**) the message showed is below.

![image](https://user-images.githubusercontent.com/9938947/109150512-e192eb80-7760-11eb-82c4-c8f92852075f.png)

And in the same browser with **192.168.x.xx:8080**, i see the right page.
So when i want to make videoconfrence this page below appear.

![](https://user-images.githubusercontent.com/9938947/109138811-af7a8d00-7752-11eb-80d3-79a508ed1db1.png)

Please can you help me?
Best regards

**NAS Synoloy DS 218+
RAM: 10 GO**

**Comment by saghul** [comment]
We don't maintain the Synology packages, please ask the author.

**Comment by TosoBoso** [comment]
All, greeting from the author of Synology Jitsi Package the **root cause** is the following:

Jitsi introduced the use of Websockets as default which has to be reflected in case of it being run behind a reverse proxy.
This is the default setup of the Synology Jitsi Docker Package. This Package is a nice wrapper with GUI and mod scripts but essentially it just uses Docker-Compose so the issue was introduced within the Websockets "breaking change" for ReverseProxy.

The **resolution** is the following (no new package needed):
On Synology DSM go for control panel -> application portal -> Reverse Proxy for your respective entry. There go custom header, create websockets (see screenshot)
[https://www.synology-forum.de/attachments/jitsi-rproxy-png.60537/](url)

@saghul: appreciate you don't maintain the Jitsi Synology packages, however a hint by the core team on the websockets and potential issues with reverse proxy plus routing the issue rather than closing would have really helped.
Instead I had to do hours of debugging and searching in forums until I found the reason: ReverseProxy WebSockets "awareness".
See here https://community.jitsi.org/t/how-i-disable-websockets-in-newer-latest-docker-jitsi-versions/87810 & here https://community.jitsi.org/t/jitsi-dockers-and-synology-nas/17284/16

**Comment by saghul** [comment]
From the changelog:

> Important: This release should fix some update problems users found in -1 and -2 versions. The main problem observed is the introduction of XMPP WebSockets, which requires extra configuration for the /xmpp-wesocket route if a reverse proxy is used in front of this setup. Pure docker-compose installations don't need any changes.

**Comment by TosoBoso** [comment]
Stating change log now retrospectivly is not the point. Hinting at the changelog when the issue was raised would have been great. However we are not in a perfect world.

**Comment by saghul** [comment]
I would have done that, had I known from the original report what the root cause was, but I didn't. Sorry about that.
