### ISSUE TITLE
Deploying Jitsi Web Docker Container On ECS  Fails -Retrieving Env Values.  

### ISSUE THREAD

**Issue by pnduati** [jitsi/docker-jitsi-meet#986]
Deploying Jitsi on AWS ECS, all the other docker containers run as expected but the web docker container exist with the following error
FATAL ERROR: Jicofo component secret and auth password must be set
FATAL ERROR: Jicofo component secret and auth password must be set
Looked into the part of the code that does validation and I found
prosody - https://github.com/jitsi/docker-jitsi-meet/blob/ec570baee661838622e69735a5aa26123a4bd769/prosody/rootfs/etc/cont-init.d/10-config#L32
jicofo - https://github.com/jitsi/docker-jitsi-meet/blob/0f541c82418ca31f756afdf8bfb1af6de6b0963b/jicofo/rootfs/etc/cont-init.d/10-config#L3

I'm currently setting the values JICOFO_COMPONENT_SECRET & JICOFO_AUTH_PASSWORD in the task definition.
 An example of setting the value JICOFO_COMPONENT_SECRET and JICOFO_AUTH_PASSWORD

![Amazon_ECS_Task_Definition](https://user-images.githubusercontent.com/37333652/111330161-c3921a00-8680-11eb-99bf-3344e7299d3b.png)
![Amazon_ECS_Auth_Password](https://user-images.githubusercontent.com/37333652/111330735-44e9ac80-8681-11eb-96bb-e38f1a48b560.png)

**Comment by nunofernandes** [comment]
Hi there,

I can't pinpoint the issue with this. All I can say is that I have jitsi working fine with ECS. All jitsi components run in different ECS Services so that I can scale them independently. Was able to scale to hundreds of concurrent meetings without issues but it took quite an effort to put all the pieces together (specially the autoscaling part).

From your screenshots I only see one task definition (called `wazi-video-jitsi-meet:18`) do you use different task definitions to the other components? If so, do they all share the same environment variables (this is an important one as it hit me some times).

Also, I'm using quite an old version (4857) and I do need to update to the latest one (assuming that you are using that one).

**Comment by zamarawka** [comment]
@nunofernandes do you run on fargate or ec2?

**Comment by saghul** [comment]
This seems to be ECS related and not related to this setup per se. Please feel free to continue the discussion in our community forum.
